GET http://localhost:8083/api/todos/1
GET http://localhost:8083/api/todos/byuser/1


GET http://localhost:8083/api/users

GET http://localhost:8083/api/categories

GET http://localhost:8083/api/todos
